slice_name: "\u0422\u043E\u043F \u043F\u0440\u043E\u0432\u0438\u043D\u0446\u0438\u0439\
  \ \u043F\u043E \u043F\u0440\u043E\u0434\u0430\u0436\u0430\u043C"
description: null
certified_by: null
certification_details: null
viz_type: treemap_v2
params:
  datasource: 59__table
  viz_type: treemap_v2
  slice_id: 205
  groupby:
  - province
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: sales
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 823
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\u041F\u0440\u043E\u0434\u0430\u0436\u0438"
    optionName: metric_z0ppsvkq3wl_daawcvvqf1c
  row_limit: 10000
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_wo4ltsi0d5l_a353zxazm0k
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: order_date
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_jqwhfs12tqk_87ppe2zxip
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: "DATE(TO_CHAR(order_date, 'YYYY-mm-01')) = \n  DATE('\n{% if filter_values('month_date')|length\
      \ %}\n\t{{ filter_values('month_date')[0] }}\n{% else %}\n\t2010-04-01\n{% endif\
      \ %}\n')"
    subject: null
  color_scheme: supersetColors
  show_labels: true
  show_upper_labels: true
  label_type: key_value
  number_format: $,.2f
  date_format: smart_date
  extra_form_data: {}
  dashboards:
  - 12
query_context: "{\"datasource\":{\"id\":59,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"filters\":[{\"col\":\"order_date\",\"op\":\"TEMPORAL_RANGE\",\"val\"\
  :\"No filter\"}],\"extras\":{\"having\":\"\",\"where\":\"(DATE(TO_CHAR(order_date,\
  \ 'YYYY-mm-01')) = \\n  DATE('\\n{% if filter_values('month_date')|length %}\\n\\\
  t{{ filter_values('month_date')[0] }}\\n{% else %}\\n\\t2010-04-01\\n{% endif %}\\\
  n'))\"},\"applied_time_extras\":{},\"columns\":[\"province\"],\"metrics\":[{\"expressionType\"\
  :\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"\
  certified_by\":null,\"column_name\":\"sales\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":823,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"REAL\",\"type_generic\":0,\"\
  verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"SUM\",\"sqlExpression\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"label\":\"\u041F\u0440\
  \u043E\u0434\u0430\u0436\u0438\",\"optionName\":\"metric_z0ppsvkq3wl_daawcvvqf1c\"\
  }],\"annotation_layers\":[],\"row_limit\":10000,\"series_limit\":0,\"order_desc\"\
  :true,\"url_params\":{},\"custom_params\":{},\"custom_form_data\":{}}],\"form_data\"\
  :{\"datasource\":\"59__table\",\"viz_type\":\"treemap_v2\",\"slice_id\":205,\"groupby\"\
  :[\"province\"],\"metric\":{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"sales\"\
  ,\"description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"\
  id\":823,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"\
  type\":\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"\
  aggregate\":\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :true,\"label\":\"\u041F\u0440\u043E\u0434\u0430\u0436\u0438\",\"optionName\":\"\
  metric_z0ppsvkq3wl_daawcvvqf1c\"},\"row_limit\":10000,\"adhoc_filters\":[{\"clause\"\
  :\"WHERE\",\"comparator\":\"No filter\",\"datasourceWarning\":false,\"expressionType\"\
  :\"SIMPLE\",\"filterOptionName\":\"filter_wo4ltsi0d5l_a353zxazm0k\",\"isExtra\"\
  :false,\"isNew\":false,\"operator\":\"TEMPORAL_RANGE\",\"sqlExpression\":null,\"\
  subject\":\"order_date\"},{\"clause\":\"WHERE\",\"comparator\":null,\"datasourceWarning\"\
  :false,\"expressionType\":\"SQL\",\"filterOptionName\":\"filter_jqwhfs12tqk_87ppe2zxip\"\
  ,\"isExtra\":false,\"isNew\":false,\"operator\":null,\"sqlExpression\":\"DATE(TO_CHAR(order_date,\
  \ 'YYYY-mm-01')) = \\n  DATE('\\n{% if filter_values('month_date')|length %}\\n\\\
  t{{ filter_values('month_date')[0] }}\\n{% else %}\\n\\t2010-04-01\\n{% endif %}\\\
  n')\",\"subject\":null}],\"color_scheme\":\"supersetColors\",\"show_labels\":true,\"\
  show_upper_labels\":true,\"label_type\":\"key_value\",\"number_format\":\"$,.2f\"\
  ,\"date_format\":\"smart_date\",\"extra_form_data\":{},\"dashboards\":[12],\"force\"\
  :false,\"result_format\":\"json\",\"result_type\":\"full\"},\"result_format\":\"\
  json\",\"result_type\":\"full\"}"
cache_timeout: null
uuid: 7a5a9f59-7cdc-4bd2-abd0-d5e25e1c8d4a
version: 1.0.0
dataset_uuid: 877d9add-cc7e-4543-9600-221172e84883
