slice_name: "\u0414\u0438\u043D\u0430\u043C\u0438\u043A\u0430 \u043F\u0440\u043E\u0434\
  \u0430\u0436"
description: null
certified_by: null
certification_details: null
viz_type: mixed_timeseries
params:
  datasource: 59__table
  viz_type: mixed_timeseries
  slice_id: 206
  x_axis:
    expressionType: SQL
    label: order_date
    sqlExpression: TO_CHAR(order_date, 'YYYY-mm-01')
  time_grain_sqla: P1D
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: sales
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 823
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: "\u041F\u0440\u043E\u0434\u0430\u0436\u0438, $"
    optionName: metric_mspqsipf8e_fd33g8ca1rg
    sqlExpression: null
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: order_date
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  comparison_type: values
  metrics_b:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: sales
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 823
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: "\u041F\u0440\u0435\u0434\u044B\u0434\u0443\u0449\u0438\u0439 \u0438 \u0442\
      \u0435\u043A\u0443\u0449\u0438\u0439 \u0433\u043E\u0434, $"
    optionName: metric_76ftcierq73_wkolt061ssj
    sqlExpression: null
  groupby_b: []
  adhoc_filters_b:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_t019bz2xtdp_mgu7tgx8mbi
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: order_date
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_2opwxy3ri48_hlu37kz733r
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: "DATE(TO_CHAR(order_date, 'YYYY-mm-01')) in ( \n  DATE('\n{% if\
      \ filter_values('month_date')|length %}\n\t{{ filter_values('month_date')[0]\
      \ }}\n{% else %}\n\t2010-04-01\n{% endif %}\n') - interval '1 year' \n  , DATE('\n\
      {% if filter_values('month_date')|length %}\n\t{{ filter_values('month_date')[0]\
      \ }}\n{% else %}\n\t2010-04-01\n{% endif %}\n'))"
    subject: null
  order_desc_b: true
  row_limit_b: 10000
  truncate_metric_b: true
  comparison_type_b: values
  annotation_layers: []
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  color_scheme: supersetColors
  seriesType: line
  opacity: 0.2
  markerSize: 6
  seriesTypeB: line
  stackB: false
  areaB: false
  show_valueB: false
  opacityB: 0.2
  markerEnabledB: true
  markerSizeB: 6
  show_legend: false
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_bounds_secondary:
  - null
  - null
  y_axis_format_secondary: SMART_NUMBER
  extra_form_data: {}
  dashboards:
  - 12
query_context: "{\"datasource\":{\"id\":59,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"filters\":[{\"col\":\"order_date\",\"op\":\"TEMPORAL_RANGE\",\"val\"\
  :\"No filter\"}],\"extras\":{\"time_grain_sqla\":\"P1D\",\"having\":\"\",\"where\"\
  :\"\"},\"applied_time_extras\":{},\"columns\":[{\"timeGrain\":\"P1D\",\"columnType\"\
  :\"BASE_AXIS\",\"expressionType\":\"SQL\",\"label\":\"order_date\",\"sqlExpression\"\
  :\"TO_CHAR(order_date, 'YYYY-mm-01')\"}],\"metrics\":[{\"aggregate\":\"SUM\",\"\
  column\":{\"advanced_data_type\":null,\"certification_details\":null,\"certified_by\"\
  :null,\"column_name\":\"sales\",\"description\":null,\"expression\":null,\"filterable\"\
  :true,\"groupby\":true,\"id\":823,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\"\
  :null,\"type\":\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\"\
  :null},\"datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\"\
  :true,\"label\":\"\u041F\u0440\u043E\u0434\u0430\u0436\u0438, $\",\"optionName\"\
  :\"metric_mspqsipf8e_fd33g8ca1rg\",\"sqlExpression\":null}],\"annotation_layers\"\
  :[],\"row_limit\":10000,\"series_columns\":[],\"series_limit\":0,\"url_params\"\
  :{},\"custom_params\":{},\"custom_form_data\":{},\"time_offsets\":[],\"post_processing\"\
  :[{\"operation\":\"pivot\",\"options\":{\"index\":[\"order_date\"],\"columns\":[],\"\
  aggregates\":{\"\u041F\u0440\u043E\u0434\u0430\u0436\u0438, $\":{\"operator\":\"\
  mean\"}},\"drop_missing_columns\":true}},{\"operation\":\"flatten\"}],\"orderby\"\
  :[[{\"aggregate\":\"SUM\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"sales\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":823,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"REAL\",\"type_generic\":0,\"\
  verbose_name\":null,\"warning_markdown\":null},\"datasourceWarning\":false,\"expressionType\"\
  :\"SIMPLE\",\"hasCustomLabel\":true,\"label\":\"\u041F\u0440\u043E\u0434\u0430\u0436\
  \u0438, $\",\"optionName\":\"metric_mspqsipf8e_fd33g8ca1rg\",\"sqlExpression\":null},false]]},{\"\
  filters\":[{\"col\":\"order_date\",\"op\":\"TEMPORAL_RANGE\",\"val\":\"No filter\"\
  }],\"extras\":{\"time_grain_sqla\":\"P1D\",\"having\":\"\",\"where\":\"(DATE(TO_CHAR(order_date,\
  \ 'YYYY-mm-01')) in ( \\n  DATE('\\n{% if filter_values('month_date')|length %}\\\
  n\\t{{ filter_values('month_date')[0] }}\\n{% else %}\\n\\t2010-04-01\\n{% endif\
  \ %}\\n') - interval '1 year' \\n  , DATE('\\n{% if filter_values('month_date')|length\
  \ %}\\n\\t{{ filter_values('month_date')[0] }}\\n{% else %}\\n\\t2010-04-01\\n{%\
  \ endif %}\\n')))\"},\"applied_time_extras\":{},\"columns\":[{\"timeGrain\":\"P1D\"\
  ,\"columnType\":\"BASE_AXIS\",\"expressionType\":\"SQL\",\"label\":\"order_date\"\
  ,\"sqlExpression\":\"TO_CHAR(order_date, 'YYYY-mm-01')\"}],\"metrics\":[{\"aggregate\"\
  :\"SUM\",\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"\
  certified_by\":null,\"column_name\":\"sales\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":823,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"REAL\",\"type_generic\":0,\"\
  verbose_name\":null,\"warning_markdown\":null},\"datasourceWarning\":false,\"expressionType\"\
  :\"SIMPLE\",\"hasCustomLabel\":true,\"label\":\"\u041F\u0440\u0435\u0434\u044B\u0434\
  \u0443\u0449\u0438\u0439 \u0438 \u0442\u0435\u043A\u0443\u0449\u0438\u0439 \u0433\
  \u043E\u0434, $\",\"optionName\":\"metric_76ftcierq73_wkolt061ssj\",\"sqlExpression\"\
  :null}],\"annotation_layers\":[],\"row_limit\":10000,\"series_columns\":[],\"series_limit\"\
  :0,\"url_params\":{},\"custom_params\":{},\"custom_form_data\":{},\"time_offsets\"\
  :[],\"post_processing\":[{\"operation\":\"pivot\",\"options\":{\"index\":[\"order_date\"\
  ],\"columns\":[],\"aggregates\":{\"\u041F\u0440\u0435\u0434\u044B\u0434\u0443\u0449\
  \u0438\u0439 \u0438 \u0442\u0435\u043A\u0443\u0449\u0438\u0439 \u0433\u043E\u0434\
  , $\":{\"operator\":\"mean\"}},\"drop_missing_columns\":true}},{\"operation\":\"\
  flatten\"}],\"orderby\":[[{\"aggregate\":\"SUM\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"sales\"\
  ,\"description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"\
  id\":823,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"\
  type\":\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"\
  datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\":true,\"\
  label\":\"\u041F\u0440\u0435\u0434\u044B\u0434\u0443\u0449\u0438\u0439 \u0438 \u0442\
  \u0435\u043A\u0443\u0449\u0438\u0439 \u0433\u043E\u0434, $\",\"optionName\":\"metric_76ftcierq73_wkolt061ssj\"\
  ,\"sqlExpression\":null},false]]}],\"form_data\":{\"datasource\":\"59__table\",\"\
  viz_type\":\"mixed_timeseries\",\"slice_id\":206,\"x_axis\":{\"expressionType\"\
  :\"SQL\",\"label\":\"order_date\",\"sqlExpression\":\"TO_CHAR(order_date, 'YYYY-mm-01')\"\
  },\"time_grain_sqla\":\"P1D\",\"metrics\":[{\"aggregate\":\"SUM\",\"column\":{\"\
  advanced_data_type\":null,\"certification_details\":null,\"certified_by\":null,\"\
  column_name\":\"sales\",\"description\":null,\"expression\":null,\"filterable\"\
  :true,\"groupby\":true,\"id\":823,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\"\
  :null,\"type\":\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\"\
  :null},\"datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\"\
  :true,\"label\":\"\u041F\u0440\u043E\u0434\u0430\u0436\u0438, $\",\"optionName\"\
  :\"metric_mspqsipf8e_fd33g8ca1rg\",\"sqlExpression\":null}],\"groupby\":[],\"adhoc_filters\"\
  :[{\"clause\":\"WHERE\",\"comparator\":\"No filter\",\"expressionType\":\"SIMPLE\"\
  ,\"operator\":\"TEMPORAL_RANGE\",\"subject\":\"order_date\"}],\"order_desc\":true,\"\
  row_limit\":10000,\"truncate_metric\":true,\"comparison_type\":\"values\",\"annotation_layers\"\
  :[],\"x_axis_title_margin\":15,\"y_axis_title_margin\":15,\"y_axis_title_position\"\
  :\"Left\",\"color_scheme\":\"supersetColors\",\"seriesType\":\"line\",\"opacity\"\
  :0.2,\"markerSize\":6,\"seriesTypeB\":\"line\",\"stackB\":false,\"areaB\":false,\"\
  show_valueB\":false,\"opacityB\":0.2,\"markerEnabledB\":true,\"markerSizeB\":6,\"\
  show_legend\":false,\"x_axis_time_format\":\"smart_date\",\"rich_tooltip\":true,\"\
  tooltipTimeFormat\":\"smart_date\",\"truncateXAxis\":true,\"y_axis_bounds\":[null,null],\"\
  y_axis_format\":\"SMART_NUMBER\",\"y_axis_bounds_secondary\":[null,null],\"y_axis_format_secondary\"\
  :\"SMART_NUMBER\",\"extra_form_data\":{},\"dashboards\":[12],\"force\":false,\"\
  result_format\":\"json\",\"result_type\":\"full\"},\"result_format\":\"json\",\"\
  result_type\":\"full\"}"
cache_timeout: null
uuid: 559fab2e-b7c5-4c6a-b0ae-20e37280f22f
version: 1.0.0
dataset_uuid: 877d9add-cc7e-4543-9600-221172e84883
