slice_name: "\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043A\u0430 \u043F\u043E\
  \ \u043F\u043E\u0434\u043A\u0430\u0442\u0435\u0433\u043E\u0440\u0438\u044F\u043C"
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 59__table
  viz_type: table
  slice_id: 207
  query_mode: aggregate
  groupby:
  - expressionType: SQL
    label: Product Category
    sqlExpression: product_category
  - expressionType: SQL
    label: Product Sub-Category
    sqlExpression: product_subcategory
  time_grain_sqla: P1M
  temporal_columns_lookup:
    order_date: true
    order_month_date: true
    ship_date: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: profit
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 826
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: "\u041F\u0440\u0438\u0431\u044B\u043B\u044C"
    optionName: metric_slc9bncmxm_rie2vkb9m9s
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: sales
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 823
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: "\u041F\u0440\u043E\u0434\u0430\u0436\u0438"
    optionName: metric_n2yuk4ayotm_pynebb0jhs
    sqlExpression: null
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_px9oa2ool59_sjut835afne
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: order_date
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_jeek4rbl8lb_mxd3xz2p63c
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: "DATE(TO_CHAR(order_date, 'YYYY-mm-01')) = \n  DATE('\n{% if filter_values('month_date')|length\
      \ %}\n\t{{ filter_values('month_date')[0] }}\n{% else %}\n\t2010-04-01\n{% endif\
      \ %}\n')"
    subject: null
  timeseries_limit_metric:
    aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: false
    label: concat(product_category, product_subcategory)
    optionName: metric_gb9wwt31sys_raicz951uk9
    sqlExpression: concat(product_category, product_subcategory)
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: false
  show_totals: false
  table_timestamp_format: smart_date
  allow_rearrange_columns: false
  allow_render_html: true
  column_config:
    product_category:
      truncateLongCells: false
    "\u041F\u0440\u0438\u0431\u044B\u043B\u044C":
      d3NumberFormat: $,.2f
      d3SmallNumberFormat: $,.2f
    "\u041F\u0440\u043E\u0434\u0430\u0436\u0438":
      d3NumberFormat: $,.2f
      d3SmallNumberFormat: $,.2f
  show_cell_bars: true
  align_pn: false
  color_pn: true
  comparison_color_scheme: Green
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 12
query_context: "{\"datasource\":{\"id\":59,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"filters\":[{\"col\":\"order_date\",\"op\":\"TEMPORAL_RANGE\",\"val\"\
  :\"No filter\"}],\"extras\":{\"having\":\"\",\"where\":\"(DATE(TO_CHAR(order_date,\
  \ 'YYYY-mm-01')) = \\n  DATE('\\n{% if filter_values('month_date')|length %}\\n\\\
  t{{ filter_values('month_date')[0] }}\\n{% else %}\\n\\t2010-04-01\\n{% endif %}\\\
  n'))\"},\"applied_time_extras\":{},\"columns\":[{\"expressionType\":\"SQL\",\"label\"\
  :\"Product Category\",\"sqlExpression\":\"product_category\"},{\"expressionType\"\
  :\"SQL\",\"label\":\"Product Sub-Category\",\"sqlExpression\":\"product_subcategory\"\
  }],\"metrics\":[{\"aggregate\":\"SUM\",\"column\":{\"advanced_data_type\":null,\"\
  certification_details\":null,\"certified_by\":null,\"column_name\":\"profit\",\"\
  description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\"\
  :826,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"type\"\
  :\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"\
  datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\":true,\"\
  label\":\"\u041F\u0440\u0438\u0431\u044B\u043B\u044C\",\"optionName\":\"metric_slc9bncmxm_rie2vkb9m9s\"\
  ,\"sqlExpression\":null},{\"aggregate\":\"SUM\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"sales\"\
  ,\"description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"\
  id\":823,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"\
  type\":\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"\
  datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\":true,\"\
  label\":\"\u041F\u0440\u043E\u0434\u0430\u0436\u0438\",\"optionName\":\"metric_n2yuk4ayotm_pynebb0jhs\"\
  ,\"sqlExpression\":null}],\"orderby\":[[{\"aggregate\":null,\"column\":null,\"datasourceWarning\"\
  :false,\"expressionType\":\"SQL\",\"hasCustomLabel\":false,\"label\":\"concat(product_category,\
  \ product_subcategory)\",\"optionName\":\"metric_gb9wwt31sys_raicz951uk9\",\"sqlExpression\"\
  :\"concat(product_category, product_subcategory)\"},true]],\"annotation_layers\"\
  :[],\"row_limit\":1000,\"series_limit\":0,\"series_limit_metric\":{\"aggregate\"\
  :null,\"column\":null,\"datasourceWarning\":false,\"expressionType\":\"SQL\",\"\
  hasCustomLabel\":false,\"label\":\"concat(product_category, product_subcategory)\"\
  ,\"optionName\":\"metric_gb9wwt31sys_raicz951uk9\",\"sqlExpression\":\"concat(product_category,\
  \ product_subcategory)\"},\"order_desc\":false,\"url_params\":{},\"custom_params\"\
  :{},\"custom_form_data\":{},\"post_processing\":[],\"time_offsets\":[]}],\"form_data\"\
  :{\"datasource\":\"59__table\",\"viz_type\":\"table\",\"slice_id\":207,\"query_mode\"\
  :\"aggregate\",\"groupby\":[{\"expressionType\":\"SQL\",\"label\":\"Product Category\"\
  ,\"sqlExpression\":\"product_category\"},{\"expressionType\":\"SQL\",\"label\":\"\
  Product Sub-Category\",\"sqlExpression\":\"product_subcategory\"}],\"time_grain_sqla\"\
  :\"P1M\",\"temporal_columns_lookup\":{\"order_date\":true,\"order_month_date\":true,\"\
  ship_date\":true},\"metrics\":[{\"aggregate\":\"SUM\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"profit\"\
  ,\"description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"\
  id\":826,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"\
  type\":\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"\
  datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\":true,\"\
  label\":\"\u041F\u0440\u0438\u0431\u044B\u043B\u044C\",\"optionName\":\"metric_slc9bncmxm_rie2vkb9m9s\"\
  ,\"sqlExpression\":null},{\"aggregate\":\"SUM\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"sales\"\
  ,\"description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"\
  id\":823,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"\
  type\":\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"\
  datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\":true,\"\
  label\":\"\u041F\u0440\u043E\u0434\u0430\u0436\u0438\",\"optionName\":\"metric_n2yuk4ayotm_pynebb0jhs\"\
  ,\"sqlExpression\":null}],\"all_columns\":[],\"percent_metrics\":[],\"adhoc_filters\"\
  :[{\"clause\":\"WHERE\",\"comparator\":\"No filter\",\"datasourceWarning\":false,\"\
  expressionType\":\"SIMPLE\",\"filterOptionName\":\"filter_px9oa2ool59_sjut835afne\"\
  ,\"isExtra\":false,\"isNew\":false,\"operator\":\"TEMPORAL_RANGE\",\"sqlExpression\"\
  :null,\"subject\":\"order_date\"},{\"clause\":\"WHERE\",\"comparator\":null,\"datasourceWarning\"\
  :false,\"expressionType\":\"SQL\",\"filterOptionName\":\"filter_jeek4rbl8lb_mxd3xz2p63c\"\
  ,\"isExtra\":false,\"isNew\":false,\"operator\":null,\"sqlExpression\":\"DATE(TO_CHAR(order_date,\
  \ 'YYYY-mm-01')) = \\n  DATE('\\n{% if filter_values('month_date')|length %}\\n\\\
  t{{ filter_values('month_date')[0] }}\\n{% else %}\\n\\t2010-04-01\\n{% endif %}\\\
  n')\",\"subject\":null}],\"timeseries_limit_metric\":{\"aggregate\":null,\"column\"\
  :null,\"datasourceWarning\":false,\"expressionType\":\"SQL\",\"hasCustomLabel\"\
  :false,\"label\":\"concat(product_category, product_subcategory)\",\"optionName\"\
  :\"metric_gb9wwt31sys_raicz951uk9\",\"sqlExpression\":\"concat(product_category,\
  \ product_subcategory)\"},\"order_by_cols\":[],\"row_limit\":1000,\"server_page_length\"\
  :10,\"order_desc\":false,\"show_totals\":false,\"table_timestamp_format\":\"smart_date\"\
  ,\"allow_rearrange_columns\":false,\"allow_render_html\":true,\"column_config\"\
  :{\"product_category\":{\"truncateLongCells\":false},\"\u041F\u0440\u0438\u0431\u044B\
  \u043B\u044C\":{\"d3NumberFormat\":\"$,.2f\",\"d3SmallNumberFormat\":\"$,.2f\"},\"\
  \u041F\u0440\u043E\u0434\u0430\u0436\u0438\":{\"d3NumberFormat\":\"$,.2f\",\"d3SmallNumberFormat\"\
  :\"$,.2f\"}},\"show_cell_bars\":true,\"align_pn\":false,\"color_pn\":true,\"comparison_color_scheme\"\
  :\"Green\",\"conditional_formatting\":[],\"comparison_type\":\"values\",\"extra_form_data\"\
  :{},\"dashboards\":[12],\"force\":false,\"result_format\":\"json\",\"result_type\"\
  :\"full\"},\"result_format\":\"json\",\"result_type\":\"full\"}"
cache_timeout: null
uuid: 9d41cf30-03fb-40eb-b1b7-4dbcb04c92b3
version: 1.0.0
dataset_uuid: 877d9add-cc7e-4543-9600-221172e84883
