slice_name: "\u0422\u043E\u043F \u043A\u043B\u0438\u0435\u043D\u0442\u043E\u0432 \u043F\
  \u043E \u043F\u0440\u0438\u0431\u044B\u043B\u0438"
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 59__table
  viz_type: table
  query_mode: aggregate
  groupby:
  - label: Customer Segment
    sqlExpression: customer_segment
    expressionType: SQL
  - label: Customer Name
    sqlExpression: customer_name
    expressionType: SQL
  time_grain_sqla: P1M
  temporal_columns_lookup:
    order_date: true
    ship_date: true
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: profit
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 826
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\u041F\u0440\u0438\u0431\u044B\u043B\u044C"
    optionName: metric_unzjn1778gr_0bvfv4pn4rlc
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - expressionType: SIMPLE
    subject: order_date
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_sbaly477uec_q1mxfxbxg5i
  - expressionType: SQL
    sqlExpression: "DATE(TO_CHAR(order_date, 'YYYY-mm-01')) = \n  DATE('\n{% if filter_values('month_date')|length\
      \ %}\n\t{{ filter_values('month_date')[0] }}\n{% else %}\n\t2010-04-01\n{% endif\
      \ %}\n')"
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_b3smx1ldk5v_8c80jfhizfk
  timeseries_limit_metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: profit
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 826
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(profit)
    optionName: metric_hufruy1cchi_ow2tgvor5ln
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  allow_render_html: true
  column_config:
    "\u041F\u0440\u0438\u0431\u044B\u043B\u044C":
      d3NumberFormat: $,.2f
      d3SmallNumberFormat: $,.2f
      horizontalAlign: left
      columnWidth: 300
      colorPositiveNegative: false
      alignPositiveNegative: false
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 12
query_context: "{\"datasource\":{\"id\":59,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"filters\":[{\"col\":\"order_date\",\"op\":\"TEMPORAL_RANGE\",\"val\"\
  :\"No filter\"}],\"extras\":{\"having\":\"\",\"where\":\"(DATE(TO_CHAR(order_date,\
  \ 'YYYY-mm-01')) = \\n  DATE('\\n{% if filter_values('month_date')|length %}\\n\\\
  t{{ filter_values('month_date')[0] }}\\n{% else %}\\n\\t2010-04-01\\n{% endif %}\\\
  n'))\"},\"applied_time_extras\":{},\"columns\":[{\"label\":\"Customer Segment\"\
  ,\"sqlExpression\":\"customer_segment\",\"expressionType\":\"SQL\"},{\"label\":\"\
  Customer Name\",\"sqlExpression\":\"customer_name\",\"expressionType\":\"SQL\"}],\"\
  metrics\":[{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"\
  certification_details\":null,\"certified_by\":null,\"column_name\":\"profit\",\"\
  description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\"\
  :826,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"type\"\
  :\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"\
  aggregate\":\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :true,\"label\":\"\u041F\u0440\u0438\u0431\u044B\u043B\u044C\",\"optionName\":\"\
  metric_unzjn1778gr_0bvfv4pn4rlc\"}],\"orderby\":[[{\"expressionType\":\"SIMPLE\"\
  ,\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"certified_by\"\
  :null,\"column_name\":\"profit\",\"description\":null,\"expression\":null,\"filterable\"\
  :true,\"groupby\":true,\"id\":826,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\"\
  :null,\"type\":\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\"\
  :null},\"aggregate\":\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"\
  hasCustomLabel\":false,\"label\":\"SUM(profit)\",\"optionName\":\"metric_hufruy1cchi_ow2tgvor5ln\"\
  },false]],\"annotation_layers\":[],\"row_limit\":1000,\"series_limit\":0,\"series_limit_metric\"\
  :{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"profit\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":826,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"REAL\",\"type_generic\":0,\"\
  verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"SUM\",\"sqlExpression\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":false,\"label\":\"SUM(profit)\"\
  ,\"optionName\":\"metric_hufruy1cchi_ow2tgvor5ln\"},\"order_desc\":true,\"url_params\"\
  :{},\"custom_params\":{},\"custom_form_data\":{},\"post_processing\":[],\"time_offsets\"\
  :[]}],\"form_data\":{\"datasource\":\"59__table\",\"viz_type\":\"table\",\"query_mode\"\
  :\"aggregate\",\"groupby\":[{\"label\":\"Customer Segment\",\"sqlExpression\":\"\
  customer_segment\",\"expressionType\":\"SQL\"},{\"label\":\"Customer Name\",\"sqlExpression\"\
  :\"customer_name\",\"expressionType\":\"SQL\"}],\"time_grain_sqla\":\"P1M\",\"temporal_columns_lookup\"\
  :{\"order_date\":true,\"ship_date\":true},\"metrics\":[{\"expressionType\":\"SIMPLE\"\
  ,\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"certified_by\"\
  :null,\"column_name\":\"profit\",\"description\":null,\"expression\":null,\"filterable\"\
  :true,\"groupby\":true,\"id\":826,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\"\
  :null,\"type\":\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\"\
  :null},\"aggregate\":\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"\
  hasCustomLabel\":true,\"label\":\"\u041F\u0440\u0438\u0431\u044B\u043B\u044C\",\"\
  optionName\":\"metric_unzjn1778gr_0bvfv4pn4rlc\"}],\"all_columns\":[],\"percent_metrics\"\
  :[],\"adhoc_filters\":[{\"expressionType\":\"SIMPLE\",\"subject\":\"order_date\"\
  ,\"operator\":\"TEMPORAL_RANGE\",\"comparator\":\"No filter\",\"clause\":\"WHERE\"\
  ,\"sqlExpression\":null,\"isExtra\":false,\"isNew\":false,\"datasourceWarning\"\
  :false,\"filterOptionName\":\"filter_sbaly477uec_q1mxfxbxg5i\"},{\"expressionType\"\
  :\"SQL\",\"sqlExpression\":\"DATE(TO_CHAR(order_date, 'YYYY-mm-01')) = \\n  DATE('\\\
  n{% if filter_values('month_date')|length %}\\n\\t{{ filter_values('month_date')[0]\
  \ }}\\n{% else %}\\n\\t2010-04-01\\n{% endif %}\\n')\",\"clause\":\"WHERE\",\"subject\"\
  :null,\"operator\":null,\"comparator\":null,\"isExtra\":false,\"isNew\":false,\"\
  datasourceWarning\":false,\"filterOptionName\":\"filter_b3smx1ldk5v_8c80jfhizfk\"\
  }],\"timeseries_limit_metric\":{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"profit\"\
  ,\"description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"\
  id\":826,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"\
  type\":\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"\
  aggregate\":\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :false,\"label\":\"SUM(profit)\",\"optionName\":\"metric_hufruy1cchi_ow2tgvor5ln\"\
  },\"order_by_cols\":[],\"row_limit\":1000,\"server_page_length\":10,\"order_desc\"\
  :true,\"table_timestamp_format\":\"smart_date\",\"allow_render_html\":true,\"column_config\"\
  :{\"\u041F\u0440\u0438\u0431\u044B\u043B\u044C\":{\"d3NumberFormat\":\"$,.2f\",\"\
  d3SmallNumberFormat\":\"$,.2f\",\"horizontalAlign\":\"left\",\"columnWidth\":300,\"\
  colorPositiveNegative\":false,\"alignPositiveNegative\":false}},\"show_cell_bars\"\
  :true,\"color_pn\":true,\"comparison_color_scheme\":\"Green\",\"conditional_formatting\"\
  :[],\"comparison_type\":\"values\",\"extra_form_data\":{},\"dashboards\":[12],\"\
  force\":false,\"result_format\":\"json\",\"result_type\":\"full\"},\"result_format\"\
  :\"json\",\"result_type\":\"full\"}"
cache_timeout: null
uuid: 332811e1-2218-49c1-a3dc-ebd9a9f790d6
version: 1.0.0
dataset_uuid: 877d9add-cc7e-4543-9600-221172e84883
