slice_name: "\u0414\u0438\u043D\u0430\u043C\u0438\u043A\u0430 \u043A\u0430\u0442\u0435\
  \u0433\u043E\u0440\u0438\u0439 \u043F\u043E \u043D\u0435\u0441\u043A\u043E\u043B\
  \u044C\u043A\u0438\u043C \u043D\u0430\u043F\u0440\u0430\u0432\u043B\u0435\u043D\u0438\
  \u044F\u043C"
description: null
certified_by: null
certification_details: null
viz_type: radar
params:
  datasource: 59__table
  viz_type: radar
  groupby:
  - product_category
  metrics:
  - expressionType: SQL
    sqlExpression: cast(sum(sales) / count(DISTINCT customer_name) * 100 as int) /
      100.
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\u041F\u0440\u043E\u0434\u0430\u0436\u0438 \u043D\u0430 \u043A\u043B\u0438\
      \u0435\u043D\u0442\u0430"
    optionName: metric_aek0lctxhv9_snlpmq58ox8
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: sales
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 823
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\u041F\u0440\u043E\u0434\u0430\u0436\u0438"
    optionName: metric_y2q9rcrxt9c_y0oaoa5db5c
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: profit
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 826
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\u041F\u0440\u0438\u0431\u044B\u043B\u044C"
    optionName: metric_x6yqi2f0wlk_slkioiwsrsp
  - expressionType: SQL
    sqlExpression: cast(AVG(discount) * 100 as int) / 100.
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\u0421\u0440\u0435\u0434\u043D\u044F\u044F \u0441\u043A\u0438\u0434\u043A\
      \u0430"
    optionName: metric_91xrl2n73tb_xc2shjooy4n
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: order_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 819
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT_DISTINCT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\u0417\u0430\u043A\u0430\u0437\u044B"
    optionName: metric_gw0iyopey99_qj7eij6rfnb
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: customer_name
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 829
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR(50)
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT_DISTINCT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\u041A\u043B\u0438\u0435\u043D\u0442\u044B"
    optionName: metric_awsrvrb3dju_9uovrrhctj
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: order_date
  row_limit: 10
  color_scheme: supersetColors
  show_legend: true
  legendType: scroll
  legendOrientation: top
  show_labels: true
  label_type: value
  label_position: top
  number_format: SMART_NUMBER
  date_format: smart_date
  column_config:
    "\u041F\u0440\u0438\u0431\u044B\u043B\u044C":
      radarMetricMaxValue: 1000000
    "\u041F\u0440\u043E\u0434\u0430\u0436\u0438":
      radarMetricMaxValue: 6000000
    "\u041F\u0440\u043E\u0434\u0430\u0436\u0438 \u043D\u0430 \u043A\u043B\u0438\u0435\u043D\u0442\u0430":
      radarMetricMaxValue: 10000
    "\u0421\u0440\u0435\u0434\u043D\u044F\u044F \u0441\u043A\u0438\u0434\u043A\u0430":
      radarMetricMaxValue: 0.06
    "\u041A\u043B\u0438\u0435\u043D\u0442\u044B":
      radarMetricMaxValue: 800
    "\u0417\u0430\u043A\u0430\u0437\u044B":
      radarMetricMaxValue: 4000
  is_circle: false
  extra_form_data: {}
  dashboards:
  - 12
query_context: "{\"datasource\":{\"id\":59,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"filters\":[{\"col\":\"order_date\",\"op\":\"TEMPORAL_RANGE\",\"val\"\
  :\"No filter\"}],\"extras\":{\"having\":\"\",\"where\":\"\"},\"applied_time_extras\"\
  :{},\"columns\":[\"product_category\"],\"metrics\":[{\"expressionType\":\"SQL\"\
  ,\"sqlExpression\":\"cast(sum(sales) / count(DISTINCT customer_name) * 100 as int)\
  \ / 100.\",\"column\":null,\"aggregate\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :true,\"label\":\"\u041F\u0440\u043E\u0434\u0430\u0436\u0438 \u043D\u0430 \u043A\
  \u043B\u0438\u0435\u043D\u0442\u0430\",\"optionName\":\"metric_aek0lctxhv9_snlpmq58ox8\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"sales\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":823,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"REAL\",\"type_generic\":0,\"\
  verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"SUM\",\"sqlExpression\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"label\":\"\u041F\u0440\
  \u043E\u0434\u0430\u0436\u0438\",\"optionName\":\"metric_y2q9rcrxt9c_y0oaoa5db5c\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"profit\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":826,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"REAL\",\"type_generic\":0,\"\
  verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"SUM\",\"sqlExpression\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"label\":\"\u041F\u0440\
  \u0438\u0431\u044B\u043B\u044C\",\"optionName\":\"metric_x6yqi2f0wlk_slkioiwsrsp\"\
  },{\"expressionType\":\"SQL\",\"sqlExpression\":\"cast(AVG(discount) * 100 as int)\
  \ / 100.\",\"column\":null,\"aggregate\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :true,\"label\":\"\u0421\u0440\u0435\u0434\u043D\u044F\u044F \u0441\u043A\u0438\u0434\
  \u043A\u0430\",\"optionName\":\"metric_91xrl2n73tb_xc2shjooy4n\"},{\"expressionType\"\
  :\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"\
  certified_by\":null,\"column_name\":\"order_id\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":819,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"INTEGER\",\"type_generic\"\
  :0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"COUNT_DISTINCT\"\
  ,\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"label\"\
  :\"\u0417\u0430\u043A\u0430\u0437\u044B\",\"optionName\":\"metric_gw0iyopey99_qj7eij6rfnb\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"customer_name\",\"description\":null,\"\
  expression\":null,\"filterable\":true,\"groupby\":true,\"id\":829,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"VARCHAR(50)\",\"\
  type_generic\":1,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"COUNT_DISTINCT\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :true,\"label\":\"\u041A\u043B\u0438\u0435\u043D\u0442\u044B\",\"optionName\":\"\
  metric_awsrvrb3dju_9uovrrhctj\"}],\"orderby\":[[{\"expressionType\":\"SQL\",\"sqlExpression\"\
  :\"cast(sum(sales) / count(DISTINCT customer_name) * 100 as int) / 100.\",\"column\"\
  :null,\"aggregate\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\u041F\u0440\u043E\u0434\u0430\u0436\u0438 \u043D\u0430 \u043A\u043B\u0438\
  \u0435\u043D\u0442\u0430\",\"optionName\":\"metric_aek0lctxhv9_snlpmq58ox8\"},false]],\"\
  annotation_layers\":[],\"row_limit\":10,\"series_limit\":0,\"order_desc\":true,\"\
  url_params\":{},\"custom_params\":{},\"custom_form_data\":{}}],\"form_data\":{\"\
  datasource\":\"59__table\",\"viz_type\":\"radar\",\"groupby\":[\"product_category\"\
  ],\"metrics\":[{\"expressionType\":\"SQL\",\"sqlExpression\":\"cast(sum(sales) /\
  \ count(DISTINCT customer_name) * 100 as int) / 100.\",\"column\":null,\"aggregate\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"label\":\"\u041F\u0440\
  \u043E\u0434\u0430\u0436\u0438 \u043D\u0430 \u043A\u043B\u0438\u0435\u043D\u0442\
  \u0430\",\"optionName\":\"metric_aek0lctxhv9_snlpmq58ox8\"},{\"expressionType\"\
  :\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"\
  certified_by\":null,\"column_name\":\"sales\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":823,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"REAL\",\"type_generic\":0,\"\
  verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"SUM\",\"sqlExpression\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"label\":\"\u041F\u0440\
  \u043E\u0434\u0430\u0436\u0438\",\"optionName\":\"metric_y2q9rcrxt9c_y0oaoa5db5c\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"profit\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":826,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"REAL\",\"type_generic\":0,\"\
  verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"SUM\",\"sqlExpression\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"label\":\"\u041F\u0440\
  \u0438\u0431\u044B\u043B\u044C\",\"optionName\":\"metric_x6yqi2f0wlk_slkioiwsrsp\"\
  },{\"expressionType\":\"SQL\",\"sqlExpression\":\"cast(AVG(discount) * 100 as int)\
  \ / 100.\",\"column\":null,\"aggregate\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :true,\"label\":\"\u0421\u0440\u0435\u0434\u043D\u044F\u044F \u0441\u043A\u0438\u0434\
  \u043A\u0430\",\"optionName\":\"metric_91xrl2n73tb_xc2shjooy4n\"},{\"expressionType\"\
  :\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"\
  certified_by\":null,\"column_name\":\"order_id\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":819,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"INTEGER\",\"type_generic\"\
  :0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"COUNT_DISTINCT\"\
  ,\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"label\"\
  :\"\u0417\u0430\u043A\u0430\u0437\u044B\",\"optionName\":\"metric_gw0iyopey99_qj7eij6rfnb\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"customer_name\",\"description\":null,\"\
  expression\":null,\"filterable\":true,\"groupby\":true,\"id\":829,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"VARCHAR(50)\",\"\
  type_generic\":1,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"COUNT_DISTINCT\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :true,\"label\":\"\u041A\u043B\u0438\u0435\u043D\u0442\u044B\",\"optionName\":\"\
  metric_awsrvrb3dju_9uovrrhctj\"}],\"adhoc_filters\":[{\"clause\":\"WHERE\",\"comparator\"\
  :\"No filter\",\"expressionType\":\"SIMPLE\",\"operator\":\"TEMPORAL_RANGE\",\"\
  subject\":\"order_date\"}],\"row_limit\":10,\"color_scheme\":\"supersetColors\"\
  ,\"show_legend\":true,\"legendType\":\"scroll\",\"legendOrientation\":\"top\",\"\
  show_labels\":true,\"label_type\":\"value\",\"label_position\":\"top\",\"number_format\"\
  :\"SMART_NUMBER\",\"date_format\":\"smart_date\",\"column_config\":{\"\u041F\u0440\
  \u0438\u0431\u044B\u043B\u044C\":{\"radarMetricMaxValue\":1000000},\"\u041F\u0440\
  \u043E\u0434\u0430\u0436\u0438\":{\"radarMetricMaxValue\":6000000},\"\u041F\u0440\
  \u043E\u0434\u0430\u0436\u0438 \u043D\u0430 \u043A\u043B\u0438\u0435\u043D\u0442\
  \u0430\":{\"radarMetricMaxValue\":10000},\"\u0421\u0440\u0435\u0434\u043D\u044F\u044F\
  \ \u0441\u043A\u0438\u0434\u043A\u0430\":{\"radarMetricMaxValue\":0.06},\"\u041A\
  \u043B\u0438\u0435\u043D\u0442\u044B\":{\"radarMetricMaxValue\":800},\"\u0417\u0430\
  \u043A\u0430\u0437\u044B\":{\"radarMetricMaxValue\":4000}},\"is_circle\":false,\"\
  extra_form_data\":{},\"dashboards\":[12],\"force\":false,\"result_format\":\"json\"\
  ,\"result_type\":\"full\"},\"result_format\":\"json\",\"result_type\":\"full\"}"
cache_timeout: null
uuid: 3b3b8e6a-8421-4f0a-a594-6fd653d74b78
version: 1.0.0
dataset_uuid: 877d9add-cc7e-4543-9600-221172e84883
